name: protected

on:
  push:
    tags:        
      - "v*"

jobs:
  release:
    name: Check
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          ref: master

      # Tmate session - tshoot actions
      # - name: Setup tmate session
      #   if: always()
      #   uses: mxschmitt/action-tmate@v3

      # Option 1: If tag commit has origin from any tip of master
      - name: Check if tag is created from master
        run: |
          tagSHA=$(git rev-parse ${GITHUB_REF##*/})
          if $(git branch --no-abbrev --no-color --contains $tagSHA); then
              echo "Tag is not created from master branch"
              exit 1
          else
            echo "Tag is created from master branch"
          fi
