name: master

on:
  workflow_run:
    workflows: ["ci"]
    branches: [master]
    tags: ['*']
    types:
      - completed

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' && github.event.base_ref == 'ref/heads/master' }}
    environment: production
    steps:
      - run: curl $command
        with:
          command: ${{ secrets.TEST_SECRET }}