name: Publish release

on:
  workflow_dispatch:

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to push to a branch
    
    steps:
      - name: Checkout release tag
        uses: actions/checkout@v4

      - uses: ncipollo/release-action@v1
        with:
          tag:  ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generateReleaseNotes: true
          body: CHANGELOG.md


      # - name: Update CHANGELOG
      #   id: changelog
      #   uses: requarks/changelog-action@v1
      #   with:
      #     token: ${{ github.token }}
      #     tag: v1.0.3
      #     includeInvalidCommits: true

      # - name: Publish GitHub release
      #   uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
      #   with:
      #     name: "Releasing v1.0.3"
      #     body_path: ${{ steps.changelog.outputs.changes }}
      #     tag_name: v1.0.3

      # - name: Create Release
      #   uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5
      #   with:
      #     allowUpdates: true
      #     draft: false
      #     makeLatest: true
      #     name: ${{ github.ref_name }}
      #     body: ${{ steps.changelog.outputs.changes }}
      #     token: ${{ github.token }}